//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/InputActions/PauseControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PauseControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PauseControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PauseControls"",
    ""maps"": [
        {
            ""name"": ""PauseInput"",
            ""id"": ""1e6bd587-e35a-4015-b373-8f6c46c3c827"",
            ""actions"": [
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""81db647b-eb10-4323-8895-97936e7830d7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""5b56c2b0-5025-4c5c-96be-ad04e80dcf18"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // PauseInput
        m_PauseInput = asset.FindActionMap("PauseInput", throwIfNotFound: true);
        m_PauseInput_Pause = m_PauseInput.FindAction("Pause", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PauseInput
    private readonly InputActionMap m_PauseInput;
    private List<IPauseInputActions> m_PauseInputActionsCallbackInterfaces = new List<IPauseInputActions>();
    private readonly InputAction m_PauseInput_Pause;
    public struct PauseInputActions
    {
        private @PauseControls m_Wrapper;
        public PauseInputActions(@PauseControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Pause => m_Wrapper.m_PauseInput_Pause;
        public InputActionMap Get() { return m_Wrapper.m_PauseInput; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PauseInputActions set) { return set.Get(); }
        public void AddCallbacks(IPauseInputActions instance)
        {
            if (instance == null || m_Wrapper.m_PauseInputActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PauseInputActionsCallbackInterfaces.Add(instance);
            @Pause.started += instance.OnPause;
            @Pause.performed += instance.OnPause;
            @Pause.canceled += instance.OnPause;
        }

        private void UnregisterCallbacks(IPauseInputActions instance)
        {
            @Pause.started -= instance.OnPause;
            @Pause.performed -= instance.OnPause;
            @Pause.canceled -= instance.OnPause;
        }

        public void RemoveCallbacks(IPauseInputActions instance)
        {
            if (m_Wrapper.m_PauseInputActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPauseInputActions instance)
        {
            foreach (var item in m_Wrapper.m_PauseInputActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PauseInputActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PauseInputActions @PauseInput => new PauseInputActions(this);
    public interface IPauseInputActions
    {
        void OnPause(InputAction.CallbackContext context);
    }
}
